when:
  - event: pull_request
  - event: [push, tag, manual]
    branch: main

steps:
  build:
    image: golang:1.21-bookworm
    commands:
      - go build -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/shove ./cmd/shove

  lint:
    image: golang:1.21-bookworm
    commands:
      - go fmt $(go list ./... | grep -v /vendor/)
      - go vet $(go list ./... | grep -v /vendor/)

  test:
    image: golang:1.21-bookworm
    commands:
      - go test -race $(go list ./... | grep -v /vendor/)
